waymo_type = 'CustomWaymo'
waymo_root = '/localdata_ssd/waymo_dev1x/'
waymo_train_pkl = 'waymo_infos_train_2Hz_mono_front.pkl'
waymo_train_interval = 1    # 2Hz_part means interval = 5x3
waymo_val_pkl = 'waymo_infos_val_2Hz_part_mono_front.pkl'
waymo_val_interval = 1
waymo_h = 640
waymo_w = 960
waymo_h_crop = 436
waymo_w_crop = 960
nusc_type = 'CustomNusc'
nusc_root = '/localdata_ssd/nusc_dev1x/'
nusc_train_pkl = 'nuscenes_infos_train_mono_front.pkl'
nusc_val_pkl = 'nuscenes_infos_val_part_mono_front.pkl'
nusc_h = 450
nusc_w = 800
nusc_h_crop = 307
nusc_w_crop = 800
argo2_type = 'Argo2Dataset'
argo2_data_root = '/localdata_ssd/argo2_dev1x/'
argo2_train_pkl = 'argo2_infos_train_2Hz_mono_front.pkl'  
argo2_train_interval = 1    # 2Hz_part means interval = 5x3
argo2_val_pkl = 'argo2_infos_val_2Hz_part_mono_front.pkl'
argo2_val_interval = 1
argo2_h = 1024
argo2_w = 775
argo2_h_crop = 350 # start at 800//2
argo2_w_crop = 775
argo2_h_start = 400
argo2_h_crop_rel_pos = argo2_h_start / (argo2_h - argo2_h_crop)
lyft_type = 'CustomLyft'
lyft_data_root = '/localdata_ssd/lyft_dev1x/'
lyft_train_pkl = 'lyft_infos_train_mono_front.pkl' 
lyft_train_interval = 1
lyft_val_pkl = 'lyft_infos_val_mono_front.pkl'
lyft_val_interval = 2
lyft_small_h = 1024//2
lyft_small_w = 1224//2
lyft_small_h_crop = 400//2    # original 400~800
lyft_small_w_crop = lyft_small_w
lyft_small_h_start = 400//2
lyft_small_h_crop_rel_pos = lyft_small_h_start / (lyft_small_h - lyft_small_h_crop)
lyft_focal_interval_small = [0,1000]
lyft_big_h = 1080//2
lyft_big_w = 1920//2
lyft_big_h_crop = 440//2    # original 440~880
lyft_big_w_crop = lyft_big_w
lyft_big_h_start = 440//2
lyft_big_h_crop_rel_pos = lyft_big_h_start / (lyft_big_h - lyft_big_h_crop)
lyft_focal_interval_big = [1010,2000]
kitti_type = 'CustomKitti'
kitti_data_root = '/localdata_ssd/kitti_dev1x/'
kitti_train_pkl = 'kitti_infos_train.pkl'
kitti_train_interval = 1
kitti_val_pkl = 'kitti_infos_val.pkl'
kitti_val_interval = 1
kitti_num_views = 1
kitti_h = 370//2
kitti_w = 1224//2
kitti_h_crop = kitti_h
kitti_w_crop = kitti_w
K360_type = 'Kitti360Dataset'
K360_data_root = '/localdata_ssd/kitti-360_dev1x/'
K360_train_pkl = 'kitti360_infos_train.pkl' # 40000 frame
K360_train_interval = 1
K360_val_pkl = 'kitti360_infos_val.pkl' # 10000 frame
K360_val_interval = 5
K360_num_views = 1
K360_selected_cam = 'CAM0'
K360_h = 376//2
K360_w = 1408//2
K360_h_crop = K360_h
K360_w_crop = K360_w
pad_h = 448
pad_w = 960